version: "3"
services:
  database:
    image: postgres:10.0-alpine
    container_name: learning-sql
    volumes:
      - database:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
        - 54321:5432

volumes:
    database:
      external: false
